# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.4"
  - "3.3"
  - "2.7"

install:
    - pip install coveralls
    - pip install -r requirements-testing.txt

# command to run tests, e.g. python setup.py test
script:
    - coverage run --source nose_watcher setup.py test
    - flake8

after_success:
      coveralls
